#!/bin/bash

prj_path=$(dirname $0)/..

. $prj_path/scripts/j2_vars

tfn=$prj_path/configs/tion.yaml.j2

types=(lt-ble lt-uart 4s-ble 4s-uart 3s-ble 3s-uart o2-uart)
for br in "${types[@]}" ; do
  parts=(${br//-/ })
  port=${parts[1]}
  type=${parts[0]}
  ofn=configs/tion-$br.yaml
  dfn=$ofn
  if [ "$2" == "diff" ]; then
    dfn=/tmp/$ofn
  fi
  ofn=$prj_path/$ofn
  echo "Generating tion-$type config for $port connection..."
  $prj_path/scripts/mk-config.py $j2_vars -D is_prod=true -D port=$port -D type=$type >$dfn
  if [ "$2" == "diff" ]; then
    diff $dfn $ofn
    rm $dfn
  fi
  conns=(api mqtt)
  for conn in "${conns[@]}" ; do
    $prj_path/scripts/mk-config.py $j2_vars \
      -D port=$port -D type=$type -D conn=$conn -D project_source=../../components \
      >tests/gen/tion-$br-$conn.yaml
  done
done

for f in $prj_path/packages/*.j2 ; do
  tfn=$f
  ofn=${tfn%.*}
  dfn=$ofn
  if [ "$2" == "diff" ]; then
    dfn=/tmp/$(basename $ofn)
  fi
  echo "Generating $dfn..."
  jinja2 $j2_vars -D port=$port -D type=$type -o $dfn $tfn
  if [ "$2" == "diff" ]; then
    diff $dfn $ofn
    rm $dfn
  fi
done
