substitutions:
  # Board definition
  board: esp32-s3-devkitc-1

packages:
  tion.esp32_ble: !include z/esp32_ble.yaml

esphome:
  platformio_options:
    board_build.flash_mode: dio

declaration:
  - lambda: |-
      #define TION_PKG_ESP32_S3_INCLUDED
