substitutions:
  # Board definition
  board: esp32-s3-devkitc-1
  # UART0
  u0txd_pin: GPIO43
  u0rxd_pin: GPIO44
  # UART1
  u1txd_pin: GPIO17
  u1rxd_pin: GPIO18
  # USB
  usb_dm_pin: GPIO19
  usb_dp_pin: GPIO20

packages:
  tion.esp32_uart: !include z/esp32_uart.yaml

esphome:
  platformio_options:
    board_build.flash_mode: dio

declaration:
  - lambda: |-
      #define TION_PKG_ESP32_S3_INCLUDED
