substitutions:
  # Board definition
  board: lolin_s2_mini
  # UART0
  u0txd_pin: GPIO43
  u0rxd_pin: GPIO44
  # UART1
  u1txd_pin: GPIO17
  u1rxd_pin: GPIO18
  # USB
  usb_dm_pin: GPIO19
  usb_dp_pin: GPIO20

packages:
  tion.esp32_uart: !include z/esp32_uart.yaml
  z.logger_cdc: !include z/logger_cdc.yaml

declaration:
  - lambda: |-
      #define TION_PKG_ESP32_S2_INCLUDED
