substitutions:
  # Board definition
  board: esp32dev
  # UART0
  u0txd_pin: TX
  u0rxd_pin: RX

packages:
  tion.esp32_uart: !include z/esp32_uart.yaml

declaration:
  - lambda: |-
      #define TION_PKG_ESP32_INCLUDED
