substitutions:
  # Board definition
  board: esp32-c3-devkitm-1

packages:
  tion.esp32_ble: !include z/esp32_ble.yaml

esphome:
  platformio_options:
    board_build.flash_mode: dio

esp32_ble:
  enable_on_boot: false

wifi:
  on_connect:
    - ble.enable

declaration:
  - lambda: |-
      #define TION_PKG_ESP32_C3_INCLUDED
