substitutions:
  tion_conn: uart
  # Board definition
  board: esp01_1m
  board_code: $board

packages:
  # Make sure logging is not using the serial port
  z.logger_none: !include z/logger_none.yaml
  z.assert_esp: !include z/assert_esp.yaml

esp8266:
  board: $board
  restore_from_flash: true

uart:
  - id: tion_uart
    tx_pin: $tx_pin
    rx_pin: $rx_pin
    baud_rate: $baud_rate

declaration:
  - lambda: |-
      #define TION_PKG_ESP8266_INCLUDED
