packages:
  mqtt: !include mqtt.yaml

esphome:
  platformio_options:
    build_flags:
      # Включаем поддержку работы со SprutHub
      - -DTION_SPRUTHUB_SUPPORT

mqtt:
  discovery: false
  publish_nan_as_none: false

setup:
  - lambda: |-
      id(tion_climate).set_name(App.get_name().c_str());
