substitutions:
  time_platform: sntp

esphome:
  platformio_options:
    build_flags:
      # Включаем поддержку работы со SprutHub
      - -DTION_SPRUTHUB_SUPPORT

mqtt:
  discovery: false
  publish_nan_as_none: false

setup:
  - lambda: |-
      id(tion_climate).set_name(App.get_name().c_str());

declaration:
  - lambda: |-
      #ifdef TION_PKG_SPRUTHUB_INCLUDED
        #error Package spruthub.yaml already included
      #else
        #define TION_PKG_SPRUTHUB_INCLUDED
      #endif

      #ifndef TION_PKG_MQTT_INCLUDED
        #error Please enable package mqtt.yaml before spruthub.yaml
      #endif
